// Output languages offered across the app.
export const LANGUAGES = [
  { name: "English", flag: "\u{1F1FA}\u{1F1F8}" },
  { name: "Portuguese", flag: "\u{1F1E7}\u{1F1F7}" },
  { name: "Spanish", flag: "\u{1F1EA}\u{1F1F8}" },
  { name: "French", flag: "\u{1F1EB}\u{1F1F7}" },
  { name: "German", flag: "\u{1F1E9}\u{1F1EA}" },
  { name: "Italian", flag: "\u{1F1EE}\u{1F1F9}" },
  { name: "Japanese", flag: "\u{1F1EF}\u{1F1F5}" },
  { name: "Korean", flag: "\u{1F1F0}\u{1F1F7}" },
  { name: "Mandarin Chinese", flag: "\u{1F1E8}\u{1F1F3}" },
  { name: "Hindi", flag: "\u{1F1EE}\u{1F1F3}" },
  { name: "Arabic", flag: "\u{1F1F8}\u{1F1E6}" },
  { name: "Hebrew", flag: "\u{1F1EE}\u{1F1F1}" },
  { name: "Russian", flag: "\u{1F1F7}\u{1F1FA}" },
  { name: "Dutch", flag: "\u{1F1F3}\u{1F1F1}" },
  { name: "Turkish", flag: "\u{1F1F9}\u{1F1F7}" },
  { name: "Indonesian", flag: "\u{1F1EE}\u{1F1E9}" },
  { name: "Thai", flag: "\u{1F1F9}\u{1F1ED}" },
];
